### ISSUE TITLE
Supprimer django-qmixin

### ISSUE THREAD

**Issue by rodo** [novafloss/django-aggtrigg#66]
Est-ce que django-qmixin est **vraiment** nécessaire ?

**Comment by rodo** [comment]
No problem for me to not still support Django 1.6, we can depend on 1.7 minimal

**Comment by boblefrag** [comment]
Je valide aussi. PR a suivre

**Comment by boblefrag** [comment]
cf. https://github.com/novafloss/django-aggtrigg/pull/67

**Comment by boblefrag** [comment]
release faite. Je te laisse pousser sur pypi

**Comment by rodo** [comment]
https://pypi.python.org/pypi/django-aggtrigg/1.1.0
